Repository bonsai-rx/machinelearning, pull requests merged in 2024-06, with the labels that each got.

#12 Updated timeseries visualizers for kinematics model and mashup visualizers
  src/Bonsai.ML.Visualizers/KinematicComponentVisualizer.cs
  src/Bonsai.ML.Visualizers/KinematicStateVisualizer.cs
  src/Bonsai.ML.Visualizers/StateComponentVisualizer.cs
  src/Bonsai.ML.Visualizers/TimeSeriesOxyPlotBase.cs
Labels: feature

#13 Added forecast visualizers
  src/Bonsai.ML.Visualizers/Bonsai.ML.Visualizers.csproj
  src/Bonsai.ML.Visualizers/ForecastImageOverlay.cs
  src/Bonsai.ML.Visualizers/ForecastPlotOverlay.cs
  src/Bonsai.ML.Visualizers/ForecastVisualizer.cs
Labels: feature

#16 Run workflow directly from the test folder
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/Bonsai.ML.LinearDynamicalSystems.Tests.csproj
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCell/ReceptiveFieldSimpleCellTest.cs
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCell/original-receptivefield.json
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCell/receptive_field.bonsai
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCell/receptive_field.py
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCell/run_python_test.py
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCellTest/Bonsai.config
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCellTest/NuGet.config
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCellTest/run_bonsai_test.ps1
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/ReceptiveFieldSimpleCellTest/run_bonsai_test.sh
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/WorkflowHelper.cs
Labels: feature, proposal

#17 Avoid shutdown exception due to deprecated API
  tests/Bonsai.ML.LinearDynamicalSystems.Tests/Bonsai.ML.LinearDynamicalSystems.Tests.csproj
Labels: fix

#20 Allow examples to bootstrap from local packages
  docs/NuGet.config
  src/Bonsai.ML.LinearDynamicalSystems/Properties/launchSettings.json
  src/Bonsai.ML.Visualizers/Properties/launchSettings.json
  src/Bonsai.ML/Properties/launchSettings.json
Labels: feature

#21 Use state component visualizer label in Y axis
  src/Bonsai.ML.Visualizers/StateComponentVisualizer.cs
  src/Bonsai.ML.Visualizers/TimeSeriesOxyPlotBase.cs
Labels: feature
